name: chia_se_tien_sinh_hoat_tro
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.3.0
  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  dots_indicator: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  image_cropper: ^8.0.2
  flutter_zoom_drawer: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

