// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_o_gXQXe1FgP2UKxtX1lakLLkgQy_kG4',
    appId: '1:460649195522:android:9d2b256f98cad1bda91f1b',
    messagingSenderId: '460649195522',
    projectId: 'chia-se-tien-sinh-hoat-t-97a1b',
    storageBucket: 'chia-se-tien-sinh-hoat-t-97a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmvBXj2i86mCTOjWip6RhHm_MFn58NwYw',
    appId: '1:460649195522:ios:a0b629d86b108a72a91f1b',
    messagingSenderId: '460649195522',
    projectId: 'chia-se-tien-sinh-hoat-t-97a1b',
    storageBucket: 'chia-se-tien-sinh-hoat-t-97a1b.appspot.com',
    androidClientId: '460649195522-7vlckpf70ghh6atmkgfq3799kagre244.apps.googleusercontent.com',
    iosClientId: '460649195522-s2mq4apnep6k6rc1q1pc2i1ius3ea4ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.chiaSeTienSinhHoatTro',
  );

}